In [1]:
import cv2
img = cv2.imread("img1.JPG")
print(img)
#this will not open because the pictures are not there directly in the directory

None


In [2]:
import os
print(os.getcwd())  # Shows where Python is looking for the file


C:\Users\Rishabh Pandey\Desktop\ML


In [3]:
# import os
# print(os.listdir(r"C:\Users\Rishabh Pandey\Desktop\ML"))
# #this will show what are the folders or files in our location where python is searching for the file


['.ipynb_checkpoints', 'functionalityimsr.ipynb', 'New folder', 'OpenCv-checkpoint.ipynb']


In [9]:

# img = cv2.imread("New folder//img1.JPG") #BGR (0-255)
# print(img)
# print(img.shape)
# img = cv2.resize(img,(500,500))
# cv2.imshow("final",img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
# #this is how we fix it by specifying the folder

[[[127 123 129]
  [167 163 169]
  [109 105 111]
  ...
  [140 134 139]
  [160 154 159]
  [160 154 159]]

 [[138 134 140]
  [135 131 137]
  [127 123 129]
  ...
  [149 143 148]
  [136 130 135]
  [141 135 140]]

 [[118 114 120]
  [140 136 142]
  [159 155 161]
  ...
  [172 166 171]
  [155 149 154]
  [153 147 152]]

 ...

 [[ 67  62  63]
  [ 81  76  77]
  [ 75  70  71]
  ...
  [ 64  60  59]
  [ 55  51  50]
  [ 74  70  69]]

 [[ 65  60  61]
  [ 73  68  69]
  [ 63  58  59]
  ...
  [ 94  90  89]
  [ 86  82  81]
  [ 70  66  65]]

 [[ 72  67  68]
  [112 107 108]
  [ 64  59  60]
  ...
  [ 74  70  69]
  [ 81  77  76]
  [ 54  50  49]]]
(256, 256, 3)


In [12]:

# img = cv2.imread("New folder//img1.JPG",1) #BGR (0-255)
# print(img)
# print(img.shape)
# img = cv2.resize(img,(500,500))
# cv2.imshow("final",img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
# #for coloured

[[125 165 107 ... 136 156 156]
 [136 133 125 ... 145 132 137]
 [116 138 157 ... 168 151 149]
 ...
 [ 63  77  71 ...  60  51  70]
 [ 61  69  59 ...  90  82  66]
 [ 68 108  60 ...  70  77  50]]
(256, 256)


In [17]:

# img = cv2.imread("New folder//img1.JPG",0) #BGR (0-255)
# # print(img)
# print(img.shape)
# img = cv2.resize(img,(500,500))
# cv2.imshow("final",img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
# # #for greyscale

(256, 256)


In [16]:

# img = cv2.imread("New folder//img1.JPG",-1) #BGR (0-255)
# # print(img)
# print(img.shape)
# img = cv2.resize(img,(500,500))
# cv2.imshow("final",img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
# #for reducing intensity

(256, 256, 3)


In [28]:
# import cv2
# img = cv2.imread("New folder//img1.JPG",1) #BGR (0-255)
# img = cv2.resize(img,(700,700))
# txt = cv2.putText(img=img,
# text = "rishabh",
# org= (100,100),
# fontFace = cv2.FONT_HERSHEY_DUPLEX,
# fontScale= 3,
# color = (0,0,200),
# thickness = 3,
# lineType= cv2.LINE_8,
# bottomLeftOrigin = False)


# cv2.imshow("text",img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

# #for text on the image

In [32]:
# import cv2
# img = cv2.imread("New folder//img1.JPG",1) #BGR (0-255)
# img = cv2.resize(img,(700,700))
# txt = cv2.putText(img=img,
# text = "rishabh",
# org= (100,100),
# fontFace = cv2.FONT_HERSHEY_DUPLEX,
# fontScale= 3,
# color = (0,0,200),
# thickness = 3,
# lineType= cv2.LINE_8,
# bottomLeftOrigin = False)


# txt = cv2.putText(img = txt,
# text = "rishabh",
# org= (100,100),
# fontFace = cv2.FONT_HERSHEY_DUPLEX,
# fontScale= 3,
# color = (200,0,200),
# thickness = 3,
# lineType= cv2.LINE_8,
# bottomLeftOrigin = True)


# cv2.imshow("text",img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

# #for text on the image

# cv2.imshow("text",img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

# #for text on the image

In [ ]:
# import cv2
# old_img= cv2.imread("New folder//img1.jpg")
# old_img= cv2.resize(old_img,(600,600))
# new_img = cv2.line(img = old_img,pt1=(100,150),pt2=(360,150),color=(0,255,240),thickness = 4,lineType=4)
# cv2.imshow("line",old_img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
# # here point one and two on same line along same edge

In [4]:
# import cv2
# old_img= cv2.imread("New folder//img1.jpg")
# old_img= cv2.resize(old_img,(600,600))
# txt = cv2.putText(img=old_img,
# text = "rishabh",
# org= (100,150),
# fontFace = cv2.FONT_HERSHEY_DUPLEX,
# fontScale= 1,
# color = (0,0,200),
# thickness = 3,
# lineType= cv2.LINE_8,
# bottomLeftOrigin = False)

# new_img = cv2.rectangle(img = txt,pt1=(100,150),pt2=(500,500),color=(0,255,240),thickness = 4,lineType=4)
# cv2.imshow("line",old_img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [9]:
#how to MAKE ELLIPSE OR CIRCLE ON THE IMAGE
import cv2
old_img=cv2.imread("New folder\\img4.jpg")
old_img=cv2.resize(old_img,(600,600))
new_img = cv2.circle(img=old_img,center=(200,200),radius=100,color=(0,250,90),thickness=4,lineType=-1)
cv2.imshow("rish",old_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
#now to hide the image in circle
#how to MAKE ELLIPSE OR CIRCLE ON THE IMAGE
import cv2
old_img=cv2.imread("New folder\\img4.jpg")
old_img=cv2.resize(old_img,(600,600))
new_img = cv2.circle(img=old_img,center=(200,200),radius=100,color=(0,250,90),thickness=-1,lineType=-1)
cv2.imshow("rish",old_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
#how to MAKE ELLIPSE OR CIRCLE ON THE IMAGE
import cv2
old_img=cv2.imread("New folder\\img4.jpg")
old_img=cv2.resize(old_img,(600,600))

txt = cv2.putText(img=old_img,
text = "rishabh",
org= (400,385),
fontFace = cv2.FONT_HERSHEY_DUPLEX,
fontScale= 1,
color = (0,0,200),
thickness = 3,
lineType= cv2.LINE_8,
bottomLeftOrigin = False)
new_img = cv2.ellipse(img=old_img,center=(300,300),axes=(200,250),angle=30,startAngle=0,endAngle=350,color=(0,250,90),thickness=4,lineType=-1)
cv2.imshow("rish",old_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [37]:
# #To draw polygon on images
# import cv2
# import numpy as np
# old_img=cv2.imread("New folder\\img4.jpg")
# old_img=cv2.resize(old_img,(600,600))

# new_img = cv2.polylines(img=old_img,
#                        pts=[np.array([[100,400],[150,300],[200,350],[250,500],[100,500]])],isClosed= True,color=(0,250,90),thickness=4,lineType=16)
# cv2.imshow("rish",new_img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()


In [63]:
#Arithmetic operations on images, i.e. merging images
#Both resize images should be of the same size for the overlapping to work
import cv2
import numpy as np
img1=cv2.imread("New folder\\img1.jpg")
img2=cv2.imread("New folder\\img2.jpg")
img1=cv2.resize(img1,(600,600))
img2=cv2.resize(img2,(600,600))

new_img= cv2.addWeighted(img1,1,img2,0.5,1)
cv2.imshow("rish",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

